#:schema node_modules/wrangler/config-schema.json
name = "ssrslosr"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "15ccd912d8904ca2a7bde13216ba6fc7" }
]

[assets]
directory = "./public"
